name: regression-cypress-ci

on:
  push:
    branches:
      - main
      - dev
      - configuraciones/pepeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Cambia la versión según necesites

      - name: Install Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: install allure
        run: |
          curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.zip
          unzip allure-commandline.zip -d /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests and generate report
        run: |
          npm run cy:run:allure

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/

      - name: Upload Cypress Videos and Screenshots
        if: always() # This ensures that even if the tests fail, the artifacts are uploaded
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            allure-report